name: Build and release Aseprite (macOS x86)
on:
  push:
    branches:
      - main
    paths:
      - 'BuildLog.md'
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  fetch-aseprite-info:
    name: Fetch deps info
    runs-on: self-hosted
    outputs:
      download-link: ${{ steps.aseprite-link.outputs.download-link }}
      release-tag: ${{ steps.aseprite-link.outputs.release-tag }}
    steps:
      - name: Fetch Aseprite release link
        id: aseprite-link
        uses: a1393323447/fetch-release@main
        with:
          group: aseprite
          repo: aseprite
          match: Aseprite-.*?-Source.zip
          
  create-release:
    name: Create Release
    runs-on: self-hosted
    needs: fetch-aseprite-info
    permissions:
      contents: write
    outputs:
      download-link: ${{ needs.fetch-aseprite-info.outputs.download-link }}
      release-tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
          body: Aseprite ${{ needs.fetch-aseprite-info.outputs.release-tag }}
          skipIfReleaseExists: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-aseprite:
    name: Build Aseprite
    needs: create-release
    permissions:
      contents: write
    runs-on: self-hosted
    strategy:
      matrix:
        os: [macOS-13]
      fail-fast: false
    env:
      enable_ccache: 'off'
      laf_backend: 'skia'
      enable_scripting: 'on'
      skia_arch: 'x64'

    steps:
      - uses: actions/checkout@v4

      # 安装 7zip（macOS 环境需要）
      - name: Install 7zip
        run: brew install p7zip

      - name: Clone Aseprite
        shell: bash
        run: |
          git clone --recurse-submodules -j8 https://github.com/aseprite/aseprite --branch ${{ needs.create-release.outputs.release-tag }}

      - name: Install Skia
        working-directory: aseprite
        shell: bash
        run: |
          wget https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-macOS-Release-x64.zip
          unzip Skia-macOS-Release-x64.zip -d skia

      - uses: aseprite/get-ninja@main

      - name: Generating Makefiles
        shell: bash
        working-directory: aseprite
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
            -DENABLE_TESTS=OFF \
            -DENABLE_SCRIPTING=${{ env.enable_scripting }} \
            -DENABLE_CCACHE=${{ env.enable_ccache }} \
            -DLAF_BACKEND=${{ env.laf_backend }} \
            -DSKIA_DIR=$(realpath skia) \
            -DOPENSSL_USE_STATIC_LIBS=ON \
            -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-${{ env.skia_arch }})

      - name: Compiling
        shell: bash
        working-directory: aseprite
        run: |
          ninja -C build

      # 清理多余文件（只保留 app 和 data）
      - name: Clean Up Build folder
        working-directory: aseprite/build/bin
        shell: bash
        run: find . -mindepth 1 ! \( -name 'Aseprite.app' -prune -o -name 'data' -prune \) -exec rm -rf {} +

      # 创建便携模式标记
      - name: Make portable
        working-directory: aseprite/build/bin
        run: echo '# This file makes Aseprite portable' > aseprite.ini

      # 压缩打包
      - name: Make zip
        working-directory: aseprite/build/bin
        run: 7z a Aseprite-${{ needs.create-release.outputs.release-tag }}-macOS-x86.zip *

      # 上传到 Release
      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aseprite/build/bin/Aseprite-${{ needs.create-release.outputs.release-tag }}-macOS-x86.zip
          asset_name: Aseprite-${{ needs.create-release.outputs.release-tag }}-macOS-x86.zip
          tag: ${{ needs.create-release.outputs.release-tag }}
          overwrite: true
